### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by andrewferrier** [Bryley/neoai.nvim#1]
Hi this is a really nice plugin! Thanks for your hard work on it.

A few ideas for potential features which I think would be really powerful:

* Could the `shortcuts` configuration provide a `desc` field allowing a description to be added for each key? Essentially this would map to the `desc` field in `vim.keymap.set()`.
* Similarly, it would be great if shortcuts could be provided as user commands in addition to / instead of key mappings.

Thanks again!

**Comment by Bryley** [comment]
Hey, thanks for your feedback, I like these features and they should be fairly simple to add. I'll add them to the road map for a future update.
