### ISSUE TITLE
Where to paste "open_api_key_env" in LazyVim!?

### ISSUE THREAD

**Issue by jjaimealeman** [Bryley/neoai.nvim#2]
![image](https://user-images.githubusercontent.com/1428292/231886039-3ea241a2-e329-46ca-957b-ea4f43fedc2e.png)

I'm not sure where exactly to place `open_api_key_env = "**********"` while using Lazy.nvim.

At first I had it here:
```lua
  config = function()
    require("neoai").setup({
      -- Options go here
      open_api_key_env = "**********",
    })
```
But that shows the attached image error.

**Comment by Bryley** [comment]
Currently the plugin only supports reading the OpenAI API key from environment variables that way you can keep secrets out of your configuration.

That config option is meant to be what environment variable contains the key (by default `OPENAI_API_KEY`).

For example using the default plugin config you can use
```bash
$ OPENAI_API_KEY=***** nvim
```
To get up and running quickly.
You can also permanently update the key depending on what shell you're using, there are different ways of setting the environment variable usually typing something like:

```
export OPENAI_API_KEY=**********
```
Inside your `.bashrc` or `.zshrc` file.

I hope that helps. :+1:

**Comment by jjaimealeman** [comment]
I almost had it right - just had to remove the `" "` double-quotes!

It is working wonderfully!
Thank you!
