### ISSUE TITLE
Is there a way to easily jump between the NeoAI sidebar and a main buffer.

### ISSUE THREAD

**Issue by jim-at-jibba** [Bryley/neoai.nvim#32]
I am not sure if its something funky in my config. But I can navigate from the NeoAI window to one of my open buffers but not back to the sidebar. 

If the sidebar just a buffer? Is there an easy way for refocusing it?

Thanks

**Comment by mactanxin** [comment]
same here. I manually call `NeoAI` again to go back, maybe setup a key binding?

**Comment by nyngwang** [comment]
@mactanxin Is it possible to further jump to the "80% NeoAI" split above the "Prompt" after `NeoAI`?

**Comment by Bryley** [comment]
Hey, at the moment the NeoAI window acts just kinda like a popup window, so to jump to it you need to use the `NeoAI` command.
That command will do different things depending on where your cursor is and if NeoAI is currently active.

For example typing `:NeoAI` without having the window open will open the window and focus on it.
If the window is already open but is not focused, then the command will focus on the window, and if you are already focused on the window and you type the command it will close the popup window.

Hope that makes sense.
