### ISSUE TITLE
Is it possible to custom git commit format?

### ISSUE THREAD

**Issue by mactanxin** [Bryley/neoai.nvim#33]
I use [OpenCommit](https://github.com/di-sukharev/opencommit) for auto generate commit message. is it possible to hook it up with `NeoAI` or commit messages the same format?

**Comment by Bryley** [comment]
Hey, thanks for the suggestion.
Currently NeoAI is only setup to use OpenAI, it's possible in the future I might consider include better ways of generating commit messages by default, however the better commit message in NeoAI is just a small add on and not considered a feature of the plugin.

I think a better solution would be to create/use another custom plugin to work with primarily with the OpenCommit CLI.
