### ISSUE TITLE
Is it not support gpt-3.5?

### ISSUE THREAD

**Issue by 5huanghuai** [Bryley/neoai.nvim#49]
I don't have the access to the chatgpt4 and chatgpt3.5-turbo, so I change the model to "gpt-3.5". I get an error, "NeoAI Error: The model `gpt-3.5` does not exist. The problem comes from my wrong setting or the plugin ? 
Thank you very much.

**Comment by Bryley** [comment]
Hey, thanks for your question.
The model string comes straight from the ChatGPT API.
You can run a simple curl command to get the list of models your account has access to.

The instructions are here: https://platform.openai.com/docs/api-reference/models/list

Let me know if a model you find doesn't work.
